services:
  front:
    image: container.cs.vt.edu/pryan22/databaseproj:front
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy

  back:
    image: container.cs.vt.edu/pryan22/databaseproj:back
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe
      MYSQL_DATABASE: football_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./Back/mysql_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 3